---
spacewalk_admin_email: root@localhost
spacewalk_ssl_org: Spacewalk Org
spacewalk_ssl_org_unit: Spacewalk
spacewalk_ssl_set_city: My City
spacewalk_ssl_set_state: My State
spacewalk_ssl_set_country: GB
spacewalk_ssl_password: spacewalk
spacewalk_ssl_set_email: root@localhost
spacewalk_ssl_config_sslvhost: Y
spacewalk_db_backend: postgresql
spacewalk_db_name: spaceschema
spacewalk_db_user: spaceuser
spacewalk_db_password: spacepw
spacewalk_db_host: localhost
spacewalk_db_port: 5432
spacewalk_enable_tftp: Y
spacewalk_admin_password: test123
spacewalk_scripts_dir: /opt/spacewalk-scripts/

spacewalk_deb_repo_info:
 - {name: 'Ubuntu_Xenial_16_04', label: 'ubuntu-1604', repo: 'Ubuntu1604', activationkey: '1-ubuntu-1604', repo_url: 'http://de.archive.ubuntu.com/ubuntu/dists/xenial/main/binary-amd64/', arch: 'amd64-deb', checksum: 'sha256'}
 - {name: 'Ubuntu_Bionic_18_04', label: 'ubuntu-1804', repo: 'Ubuntu1804', activationkey: '1-ubuntu-1804', repo_url: 'http://archive.ubuntu.com/ubuntu/dists/bionic/main/binary-amd64/', arch: 'amd64-deb', checksum: 'sha256'}


spacewalk_child_deb_repo_info:
  - {name: 'Ubuntu_Xenial_16_04_security', label: 'ubuntu-1604-security', parent: 'ubuntu-1604', activationkey: '1-ubuntu-1604-security', repo: 'Ubuntu1604_security', repo_url: 'http://de.archive.ubuntu.com/ubuntu/dists/xenial-security/main/binary-amd64/', arch: 'amd64-deb', checksum: 'sha256'}
  - {name: 'Ubuntu_Bionic_18_04_security', label: 'ubuntu-1804-security', parent: 'ubuntu-1804', activationkey: '1-ubuntu-1804-security', repo: 'Ubuntu1804_security', repo_url: 'http://archive.ubuntu.com/ubuntu/dists/bionic-security/main/binary-amd64/', arch: 'amd64-deb', checksum: 'sha256'}

