---
- name: Install spacecmd
  yum: name=spacecmd

- name: install spacewalk-utils
  yum: name=spacewalk-utils state=present


- name: Add base channels
  command: spacewalk-common-channels -v -u {{spacewalk_user_admin}} --password={{spacewalk_admin_password}}  -a x86_64 -k unlimited 'centos6*' 'epel6*' 'centos7*' 'epel7*' 'spacewalk29*centos[67]'
  ignore_errors: true

- name: Get the trusted SSL certs
  get_url: url=http://localhost/pub/RHN-ORG-TRUSTED-SSL-CERT dest=/usr/share/rhn/RHN-ORG-TRUSTED-SSL-CERT
