---
- name: Add deb base channels
  command: spacecmd --user={{spacewalk_user_admin}} --password={{spacewalk_admin_password}} -- softwarechannel_create -n {{item.name}} -l {{item.label}} -a {{item.arch}} -c {{item.checksum}}
  ignore_errors: true
  with_items: "{{spacewalk_deb_channel_info}}"

- name: Add deb child channels
  command: spacecmd --user={{spacewalk_user_admin}} --password={{spacewalk_admin_password}} -- softwarechannel_create -n {{item.name}} -p {{item.parent}} -l {{item.label}} -a {{item.arch}} -c {{item.checksum}}
  ignore_errors: true
  with_items: "{{spacewalk_child_deb_channel_info}}"

- name: Add deb activation keys
  command: spacecmd --user={{spacewalk_user_admin}} --password={{spacewalk_admin_password}} -- activationkey_create -n {{item.label}} -b {{item.label}} -d {{item.name}}
  ignore_errors: true
  with_items: "{{spacewalk_deb_channel_info}}"

#- name: Add activation keys for deb child channels
#  command: spacecmd --user={{spacewalk_user_admin}} --password={{spacewalk_admin_password}} -- activationkey_create -n {{item.label}} -b {{item.parent}} -d {{item.name}}
#  ignore_errors: true
#  with_items: "{{spacewalk_child_deb_repo_info}}"

#- name: Associate child channels with activationkeys
#  command: spacecmd --user={{spacewalk_user_admin}} --password={{spacewalk_admin_password}} -- activationkey_addchildchannels {{item.activationkey}}  {{item.label}}
#  ignore_errors: true
#  with_items: "{{spacewalk_child_deb_repo_info}}"

- name: create repositories
  command: spacecmd --user={{spacewalk_user_admin}} --password={{spacewalk_admin_password}} -- repo_create -n {{item.name}} -u {{item.repo}} -t deb
  ignore_errors: true
  with_items: "{{spacewalk_deb_repo_info}}"

- name: link repositories
  command: spacecmd --user={{spacewalk_user_admin}} --password={{spacewalk_admin_password}} -- softwarechannel_addrepo {{item.channel}} {{item.name}}
  ignore_errors: true
  with_items: "{{spacewalk_deb_repo_info}}"

- name: Get the trusted SSL certs
  get_url: url=http://localhost/pub/RHN-ORG-TRUSTED-SSL-CERT dest=/usr/share/rhn/RHN-ORG-TRUSTED-SSL-CERT

#- name: Add cron jobs for synchronizing Debian repos
#  cron: name="{{item.name}} repo sync" minute="0" hour="7,19" job="{{spacewalk_scripts_dir}}debianSync.py --username={{spacewalk_user_admin}} --password={{spacewalk_admin_password}} --channel {{item.label}} --url {{item.repo_url}}"
#  with_items: "{{spacewalk_deb_repo_info | union(spacewalk_child_deb_repo_info)}}"
